araclazim/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace araclazim.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {

            return View();
        }

        public ActionResult istekler()
        {
            using (araclazim db = new araclazim())
            {

                return View(Tuple.Create<List<RezervasyonIstekleri>, List<Araclar>, List<Musteri>>(db.RezervasyonIstekleri.ToList(), db.Araclar.ToList(), db.Musteri.ToList()));
            }
        }

        public ActionResult aracEkle()
        {

            return View();
        }

        public ActionResult aracSil()
        {

            return View();
        }

        public ActionResult aracBilgileriniDuzenle(string plaka)
        {
            using (araclazim db = new araclazim())
            {
                return View(Tuple.Create<List<Araclar>, List<Model>, List<Marka>>(db.Araclar.Where(arc => arc.plaka == plaka).ToList(), db.Model.ToList(), db.Marka.ToList()));
            }
        }

        public ActionResult adminEkle()
        {

            return View();
        }

        public ActionResult raporlama()
        {

            return View();
        }

        public ActionResult kiradanGelenAraclar()
        {
            using (araclazim db = new araclazim())
            {
                return View(Tuple.Create<List<RezervasyonIstekleri>, List<GelenAraclar>>(db.RezervasyonIstekleri.ToList(), db.GelenAraclar.ToList()));
            }
           
        }

        public ActionResult fatura()
        {
            string rezId = (string)HttpRuntime.Cache["rezId"].ToString();
            string faturaId= (string)HttpRuntime.Cache["faturaId"].ToString();
            string gelenAracId= (string)HttpRuntime.Cache["gelenAracId"].ToString();
            int rezerve, fatura, arac;
            rezerve = Int32.Parse(rezId);
            fatura = Int32.Parse(faturaId);
            arac = Int32.Parse(gelenAracId);           
            using (araclazim db = new araclazim())
            {
               
               return View(Tuple.Create<List<RezervasyonIstekleri>, List<Fatura>, List<Musteri>, List<GelenAraclar>>(db.RezervasyonIstekleri.Where(rez =>rez.Id== rezerve).ToList(),  db.Fatura.Where(fat => fat.Id == fatura).ToList(), db.Musteri.ToList(), db.GelenAraclar.Where(gelArac => gelArac.Id == arac).ToList()));
            }
        }

        public ActionResult kiradanGelenAraclarControl(string Arac_Alis_Gun, string Arac_Alis_Ay, string Arac_Alis_Yil, string istek_numarasi, string hasarUcreti)
        {
            using (araclazim db = new araclazim())
            {
                int gecikmeUcret=0, gecikmeGunu = 0;
                int temp = 0;
                int kiralamaUcreti = 0;
                string anlasilanGunn, anlasilanAyy, anlasilanYill;
                string anlasilanTarih = "";
                GelenAraclar gelenArac = new GelenAraclar();
                gelenArac.aracTeslimTarih = Arac_Alis_Gun + "." + Arac_Alis_Ay + "." + Arac_Alis_Yil;
               
                gelenArac.hasarUcreti = Int32.Parse(hasarUcreti);
                foreach (RezervasyonIstekleri item in db.RezervasyonIstekleri.ToList())
                {
                    if (item.Id.ToString().Equals(istek_numarasi))
                    {
                        kiralamaUcreti = item.ucret;
                        gelenArac.rezIstekId = item;
                        anlasilanTarih = item.planlananTeslimTarihi;
                        break;
                    }
                }
                HttpRuntime.Cache["rezId"] = istek_numarasi;
                int anlasilanGun=0, anlasilanAy=0, anlasilanYil=0;
                if (!anlasilanTarih.Equals("aaa"))
                {
                    string[] tarih = anlasilanTarih.Split('.');
                    if (anlasilanTarih!="")
                    {
                        anlasilanGunn = tarih[0];
                        anlasilanAyy = tarih[1];
                        anlasilanYill = tarih[2];
                        anlasilanGun = Int32.Parse(anlasilanGunn);
                        anlasilanAy = Int32.Parse(anlasilanAyy);
                        anlasilanYil = Int32.Parse(anlasilanYill);
                    }
                   
                }
              
              
               
                if (anlasilanAy.ToString().Equals(Arac_Alis_Ay))//gelen ay aynı ise
                {
                    if (anlasilanGun - (Int32.Parse(Arac_Alis_Gun)) < 0)//gecikme olmuş
                    {
                        gecikmeGunu = (Int32.Parse(Arac_Alis_Gun)) - anlasilanGun;
                    }
                }
                else
                {

                    while (true)
                    {
                        if (Arac_Alis_Gun.Equals("0"))
                        {
                            //------------AYI 1 AZALTTIM
                            temp = Int32.Parse(Arac_Alis_Ay);
                            if (temp == 1)
                            {
                                temp = 12;
                            }
                            else
                            {
                                temp--;
                            }
                            Arac_Alis_Ay = temp.ToString();
                            //---------------------
                            Arac_Alis_Gun = "31";
                        }
                        if (Arac_Alis_Gun.Equals(anlasilanGun.ToString()) && Arac_Alis_Ay.Equals(anlasilanAy.ToString()))
                        {
                            break;
                        }
                        else
                        {
                            //------------GÜNÜ 1 AZALTTIM
                            temp = Int32.Parse(Arac_Alis_Gun);
                            temp--;
                            Arac_Alis_Gun = temp.ToString();
                            //---------------------
                            gecikmeGunu = gecikmeGunu + 1;
                        }

                    }
                }
                if (gecikmeGunu != 0)
                {
                    GecikmeCezalari gecikmeCezasi = new GecikmeCezalari();
                    gecikmeCezasi.gecikmeGunu = gecikmeGunu;
                    HttpRuntime.Cache["gecikmeId"] = gecikmeCezasi;
                    gecikmeCezasi.ucret = gecikmeGunu * 250;
                    gecikmeCezasi.teslimId = gelenArac;
                    db.GecikmeCezalari.Add(gecikmeCezasi);
                    gecikmeUcret = gecikmeGunu * 250;
                }
                Fatura fatura = new Fatura();
              
                fatura.ucret = gecikmeUcret + kiralamaUcreti + Int32.Parse(hasarUcreti);
                gelenArac.faturaId = fatura;
                db.Fatura.Add(fatura);
                db.GelenAraclar.Add(gelenArac);
               
                db.SaveChanges();
                HttpRuntime.Cache["faturaId"] = fatura.Id;
                HttpRuntime.Cache["gelenAracId"] = gelenArac.Id;


            }
            return RedirectToAction("fatura");
        }

        public ActionResult adminEkleControl(string kulAd, string sifre, string sifre2)
        {

            using (araclazim db = new araclazim())
            {
                bool flag = false;
                foreach (Admin item in db.Admin.ToList())
                {
                    if (kulAd.ToString().Equals(item.kullaniciAdi.ToString()))//Kullanıcı adı eşsiz mi tekrar baktır                        
                    {
                        flag = true;
                        break;
                    }
                }
                if (flag == false)//kayıt için kuladi eşsiz
                {
                    if (sifre == sifre2)
                    {
                        Admin mus3 = new Admin();
                        mus3.kullaniciAdi = kulAd;
                        mus3.sifre = sifre;
                        db.Admin.Add(mus3);
                        db.SaveChanges();
                        return RedirectToAction("adminEkle");

                    }
                    else//mesaj yada uyarı verdir şifreler den
                    {
                        return RedirectToAction("adminEkle");
                    }
                }
                else//kulanıcı adı önceden alınmış
                {


                    return RedirectToAction("adminEkle");
                }

            }
            // return RedirectToAction("Index");

        }

        public ActionResult AracEkleControl(string markalar, string txtModel, string yil, string txtPlaka, string kasa_tipi, string renk, string silindir_hacmi, string txtGunlukUcret, string yakit_tipi)
        {
            using (araclazim db = new araclazim()) //aynı plaka var mı kontrol et !!!!!!!!!!!!!
            {
                Model model1 = new Model();
                Araclar arac1 = new Araclar();

                bool flag = false;
                foreach (Model item in db.Model.ToList())
                {
                    if (txtModel.ToString().Equals(item.model.ToString()))//eğer aynı modelden varsa
                    {
                        arac1.modelId = item;
                        flag = true;
                    }
                }
                if (flag == false)//eğer model yoksa yeni bi model oluştur
                {
                    model1.model = txtModel;
                    arac1.modelId = model1;
                }


                foreach (Marka item in db.Marka.ToList())
                {
                    if (markalar.ToString().Equals(item.marka.ToString()))
                    {
                        model1.markaId = item;
                    }
                }

                arac1.yil = yil;
                arac1.plaka = txtPlaka;

araclazim/Controllers/MusteriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace araclazim.Controllers
{
    public class MusteriController : Controller
    {
        static string gizliKulAd;
        // GET: Musteri
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult isteklerim()
        {
            using (araclazim db = new araclazim())
            {
                string kulAd = (string)HttpRuntime.Cache["kulAd"].ToString();
              

                return View(Tuple.Create<List<RezervasyonIstekleri>, List<Araclar>, List<Musteri>>(db.RezervasyonIstekleri.Where(mus => mus.musteriId.kullaniciAdi == kulAd).ToList(), db.Araclar.ToList(), db.Musteri.ToList()));
            }
        }

        public ActionResult bilgilerimiDuzenle(string kulAd1, string sifre)
        {
            gizliKulAd = kulAd1;

            using (araclazim db = new araclazim())
            {

                return View(Tuple.Create<List<Musteri>, List<NufusBilgileri>, List<EhliyetBilgileri>>(db.Musteri.Where(klnc => klnc.kullaniciAdi == kulAd1 && klnc.sifre == sifre).ToList(), db.NufusBilgileri.ToList(), db.EhliyetBilgileri.ToList()));
            }
        }

        public ActionResult bilgilerimiDuzenleControl(string ad, string soyad, string tel, string adres, string email, string kulAd, string sifre)
        {
            Musteri stud;
            using (var ctx = new araclazim())
            {
                stud = ctx.Musteri.Where(s => s.kullaniciAdi == gizliKulAd).FirstOrDefault<Musteri>();
            }

            //2. change student name in disconnected mode (out of ctx scope)
            if (stud != null)
            {
                stud.ad = ad;
                stud.soyad = soyad;
                stud.telefon = tel;
                stud.adres = adres;
                stud.eMail = email;
                stud.kullaniciAdi = kulAd;
                stud.sifre = sifre;

            }

            //save modified entity using new Context
            using (var dbCtx = new araclazim())
            {
                //3. Mark entity as modified
                dbCtx.Entry(stud).State = System.Data.Entity.EntityState.Modified;

                //4. call SaveChanges
                dbCtx.SaveChanges();
            }

            //using (araclazim db = new araclazim())
            //{
            //    List< Musteri> m = db.Musteri.Where(a => a.kullaniciAdi == gizliKulAd).ToList();
            //    m[0].soyad = soyad;
            //    db.SaveChanges();

            //    foreach (var item in db.Musteri)
            //    {

            //        if (item.kullaniciAdi== gizliKulAd)
            //        {
            //            item.ad = ad;
            //            item.soyad = soyad;
            //            item.telefon = tel;
            //            item.adres = adres;
            //            item.eMail = email;
            //            item.kullaniciAdi = kulAd;
            //            item.sifre = sifre;
            //            break;
            //        }



            //    }

            //    var guncel1 = db.Musteri.Where(mus => mus.kullaniciAdi == gizliKulAd).ToList();//yine kullanıcı adına baktık.Artık nüfus id kontrol et
            //    foreach (var item1 in db.NufusBilgileri)
            //    {
            //        if (item1.Id==((Musteri)guncel1[0]).musteriNufusBilgisiId.Id)
            //        {
            //            item1.tcNo = tc;
            //            item1.babaAdi = babaAdi;
            //            item1.anaAdi = anaAdi;
            //            item1.dogumYeri = dogumYeri;
            //            item1.dogumTarihi = dogumTarihi;
            //            item1.medeniHal = medeniHal;
            //            item1.il = il;
            //            break;
            //        }





            //    }
            //    foreach (var item2 in db.EhliyetBilgileri)
            //    {
            //        if (item2.Id==((Musteri)guncel1[0]).ehliyetId.Id)
            //        {
            //            item2.ehliyetNo = ehliyetNo;
            //            item2.belgeNo = belgeNo;
            //            item2.ehliyetSinifi = ehliyetSinifi;
            //            item2.il = il2;
            //            item2.kullanilanCihaz = kulCihaz;
            //            break;
            //        }

            //    }
            //    db.SaveChanges();
            //}

            return RedirectToAction("bilgilerimiDuzenle");
        }



    }
}

araclazim/Views/Musteri/Faturalarim.cshtml
@{
    Layout = null;
}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Müşteri Paneli</title>


    <!-- CSS -->
    <link href="~/AdminPaneli/css/transdmin.css" rel="stylesheet" type="text/css" media="screen" />
    <!--[if IE 6]><link rel="stylesheet" type="text/css" media="screen" href="style/css/ie6.css" /><![endif]-->
    <!--[if IE 7]><link rel="stylesheet" type="text/css" media="screen" href="style/css/ie7.css" /><![endif]-->
    <!-- JavaScripts-->
    <script type="text/javascript" src="~/AdminPaneli/js/jquery.js"></script>
    <script type="text/javascript" src="~/AdminPaneli/js/jNice.js"></script>
</head>

<body>
    <div id="wrapper">
        <!-- h1 tag stays for the logo, you can use the a tag for linking the index page -->
        <br />

        <!-- You can name the links with lowercase, they will be transformed to uppercase by CSS, we prefered to name them with uppercase to have the same effect with disabled stylesheet -->
        <ul id="mainNav">

            <li class="logout">@Html.ActionLink("LOGOUT", "Index", "Home")</li>
        </ul>
        <!-- // #end mainNav -->

        <div id="containerHolder">
            <div id="container">
                <div id="sidebar">
                    <ul class="sideNav">
                        <li>@Html.ActionLink("Kiraladığım Araçlar", "Kiraladiklarim", "Musteri")</li>
                        <li><b>@Html.ActionLink("Faturalarım", "Faturalarim", "Musteri")</b></li>
                        <li>@Html.ActionLink("Bilgilerimi Düzenle", "bilgilerimiDuzenle", "Musteri")</li>

                    </ul>
                    <!-- // .sideNav -->
                </div>
                <!-- // #sidebar -->
                <!-- h2 stays for breadcrumbs -->

                <div id="main">
                    @using (Html.BeginForm("adminEkleControl", "Admin", FormMethod.Post, new { @class = "form-horizontal" }))
                    {
                        <form action="" class="jNice">
                            <h3>Admin Ekleme</h3>

                            <fieldset>

                                <p>
                                    <label>Kullanıcı Adı:</label>
                                    <input type="#{type}" id="#{label}" name="kulAd" required="required" />

                                </p>
                                <p>
                                    <label>Şifresi:</label>
                                    <input type="password" id="#{label}" name="sifre" required="required" />
                                </p>
                                <p>
                                    <label>Tekrar Şifresi:</label>
                                    <input type="password" id="#{label}" name="sifre2" required="required" />
                                </p>

                                <input type="submit" value="Admin Ekle" />
                            </fieldset>

                        </form>
                    }
                </div>
                <!-- // #main -->

                <div class="clear"></div>
            </div>
            <!-- // #container -->
        </div>
        <!-- // #containerHolder -->


    </div>
    <!-- // #wrapper -->
</body>
</html>

araclazim/Views/Musteri/Kiraladiklarim.cshtml
@{
    Layout = null;
}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Müşteri Paneli</title>

    <!-- CSS -->
    <link href="~/AdminPaneli/css/transdmin.css" rel="stylesheet" type="text/css" media="screen" />
    <!--[if IE 6]><link rel="stylesheet" type="text/css" media="screen" href="style/css/ie6.css" /><![endif]-->
    <!--[if IE 7]><link rel="stylesheet" type="text/css" media="screen" href="style/css/ie7.css" /><![endif]-->
    <!-- JavaScripts-->
    <script type="text/javascript" src="~/AdminPaneli/js/jquery.js"></script>
    <script type="text/javascript" src="~/AdminPaneli/js/jNice.js"></script>
</head>

<body>
    <div id="wrapper">
        <!-- h1 tag stays for the logo, you can use the a tag for linking the index page -->
        <br />

        <!-- You can name the links with lowercase, they will be transformed to uppercase by CSS, we prefered to name them with uppercase to have the same effect with disabled stylesheet -->
        <ul id="mainNav">

            <li class="logout">@Html.ActionLink("LOGOUT", "Index", "Home")</li>
        </ul>
        <!-- // #end mainNav -->

        <div id="containerHolder">
            <div id="container">
                <div id="sidebar">
                    <ul class="sideNav">
                        <li><b>@Html.ActionLink("Kiraladığım Araçlar", "Kiraladiklarim", "Musteri")</b></li>
                        <li>@Html.ActionLink("Faturalarım", "Faturalarim", "Musteri")</li>
                        <li>@Html.ActionLink("Bilgilerimi Düzenle", "bilgilerimiDuzenle", "Musteri")</li>
                       
                    </ul>
                    <!-- // .sideNav -->
                </div>
                <!-- // #sidebar -->
                <!-- h2 stays for breadcrumbs -->

                <div id="main">
                    @using (Html.BeginForm("adminEkleControl", "Admin", FormMethod.Post, new { @class = "form-horizontal" }))
                    {
                        <form action="" class="jNice">
                            <h3>Admin Ekleme</h3>

                            <fieldset>

                                <p>
                                    <label>Kullanıcı Adı:</label>
                                    <input type="#{type}" id="#{label}" name="kulAd" required="required" />

                                </p>
                                <p>
                                    <label>Şifresi:</label>
                                    <input type="password" id="#{label}" name="sifre" required="required" />
                                </p>
                                <p>
                                    <label>Tekrar Şifresi:</label>
                                    <input type="password" id="#{label}" name="sifre2" required="required" />
                                </p>

                                <input type="submit" value="Admin Ekle" />
                            </fieldset>

                        </form>
                    }
                </div>
                <!-- // #main -->

                <div class="clear"></div>
            </div>
            <!-- // #container -->
        </div>
        <!-- // #containerHolder -->


    </div>
    <!-- // #wrapper -->
</body>
</html>

araclazim/Views/Musteri/bilgilerimiDuzenle.cshtml
@model Tuple<List<Musteri>, List<NufusBilgileri>, List<EhliyetBilgileri>>

@{
    Layout = null;
}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Müşteri Paneli</title>

    <!-- CSS -->
    <link href="~/AdminPaneli/css/transdmin.css" rel="stylesheet" type="text/css" media="screen" />
    <!--[if IE 6]><link rel="stylesheet" type="text/css" media="screen" href="style/css/ie6.css" /><![endif]-->
    <!--[if IE 7]><link rel="stylesheet" type="text/css" media="screen" href="style/css/ie7.css" /><![endif]-->
    <!-- JavaScripts-->
    <script type="text/javascript" src="~/AdminPaneli/js/jquery.js"></script>
    <script type="text/javascript" src="~/AdminPaneli/js/jNice.js"></script>
</head>

<body>
    <div id="wrapper">
        <!-- h1 tag stays for the logo, you can use the a tag for linking the index page -->
        <br />

        <!-- You can name the links with lowercase, they will be transformed to uppercase by CSS, we prefered to name them with uppercase to have the same effect with disabled stylesheet -->
        <ul id="mainNav">

            <li class="logout">@Html.ActionLink("LOGOUT", "Index", "Home")</li>
        </ul>
        <!-- // #end mainNav -->

        <div id="containerHolder">
            <div id="container">
                <div id="sidebar">
                    <ul class="sideNav">
                        <li>@Html.ActionLink("Kiraladığım Araçlar", "Kiraladiklarim", "Musteri")</li>
                       
                        <li><b>@Html.ActionLink("Bilgilerimi Düzenle", "bilgilerimiDuzenle", "Musteri")</b></li>

                    </ul>
                    <!-- // .sideNav -->
                </div>
                <!-- // #sidebar -->
                <!-- h2 stays for breadcrumbs -->

                <div id="main">

                    <form action="" class="jNice">

                        <br /><br />


                        <fieldset>
                            <p>
                                <h4>UYARI: Bilgilerinizi güncelleyebilmek için tekrardan giriş yapmanız gerekmektedir.</h4>
                                <br /><br />
                                <label>Kullanıcı Adı:</label>
                                <input type="#{type}" id="#{label}" name="kulAd1" required="required" />




                            </p>
                            <p>
                                <label>Şifre:</label>
                                <input type="#{type}" id="#{label}" name="sifre" required="required" />
                            </p>
                            <p>
                                <input type="submit" value="Bilgilerimi Getir" />
                            </p>
                        </fieldset>

                        @using (Html.BeginForm("bilgilerimiDuzenleControl", "Musteri", FormMethod.Post, new { @class = "form-horizontal" }))
                        {
                        }

                        @foreach (var Musteri in Model.Item1)
                        {
                            using (Html.BeginForm("bilgilerimiDuzenleControl", "Musteri", FormMethod.Post, new { @class = "form-horizontal" }))
                            {


                                <h3>Kişisel Bigiler</h3>
                                <fieldset>

                                    <p>
                                        <label>Ad:</label>
                                        <input type="#{type}" id="#{label}" name="ad" required="required" value="@Musteri.ad" />

                                    </p>
                                    <p>
                                        <label>Soyad:</label>
                                        <input type="#{type}" id="#{label}" name="soyad" required="required" value="@Musteri.soyad" />
                                    </p>
                                    <p>
                                        <label>Telefon:</label>
                                        <input type="#{type}" id="#{label}" name="tel" required="required" value="@Musteri.telefon" />
                                    </p>

                                    <p>
                                        <label>Adres:</label>
                                        <input type="#{type}" id="#{label}" name="adres" required="required" value="@Musteri.adres" />

                                    </p>
                                    <p>
                                        <label>E-Mail:</label>
                                        <input type="#{type}" id="#{label}" name="email" required="required" value="@Musteri.eMail" />

                                    </p>
                                    <p>
                                        <label>Kullanıcı Adı:</label>
                                        <input type="#{type}" id="#{label}" name="kulAd" required="required" value="@Musteri.kullaniciAdi" />

                                    </p>
                                    <p>
                                        <label>Şifre:</label>
                                        <input type="#{type}" id="#{label}" name="sifre" required="required" value="@Musteri.sifre" />

                                    </p>


                                    <input type="submit" value="Bilgilerimi Güncelle" />

                                </fieldset>
                            }


                        }

                    </form>

                </div>
                <!-- // #main -->

                <div class="clear"></div>
            </div>
            <!-- // #container -->
        </div>
        <!-- // #containerHolder -->


    </div>
    <!-- // #wrapper -->
</body>
</html>

araclazim/Views/Musteri/isteklerim.cshtml
@model Tuple<List<RezervasyonIstekleri>, List<Araclar>, List<Musteri>>
@{
    Layout = null;
}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Müşteri Paneli</title>

    <!-- CSS -->
    <link href="~/AdminPaneli/css/transdmin.css" rel="stylesheet" type="text/css" media="screen" />
    <!--[if IE 6]><link rel="stylesheet" type="text/css" media="screen" href="style/css/ie6.css" /><![endif]-->
    <!--[if IE 7]><link rel="stylesheet" type="text/css" media="screen" href="style/css/ie7.css" /><![endif]-->
    <!-- JavaScripts-->
    <script type="text/javascript" src="~/AdminPaneli/js/jquery.js"></script>
    <script type="text/javascript" src="~/AdminPaneli/js/jNice.js"></script>
</head>

<body>
    <div id="wrapper">
        <!-- h1 tag stays for the logo, you can use the a tag for linking the index page -->
        <br />

        <!-- You can name the links with lowercase, they will be transformed to uppercase by CSS, we prefered to name them with uppercase to have the same effect with disabled stylesheet -->
        <ul id="mainNav">

            <li class="logout">@Html.ActionLink("LOGOUT", "Index", "Home")</li>
        </ul>
        <!-- // #end mainNav -->

        <div id="containerHolder">
            <div id="container">
                <div id="sidebar">
                    <ul class="sideNav">
                        <li><b>@Html.ActionLink("Yaptığım İstekler", "isteklerim", "Musteri")</b></li>
                       
                        <li>@Html.ActionLink("Bilgilerimi Düzenle", "bilgilerimiDuzenle", "Musteri")</li>
                       
                    </ul>
                    <!-- // .sideNav -->
                </div>
                <!-- // #sidebar -->
                <!-- h2 stays for breadcrumbs -->

                <div id="main">

                    <form action="" class="jNice">

                        <br /><br />                      
                       
                        @using (Html.BeginForm("aracBilgileriniDuzenleControl", "Admin", FormMethod.Post, new { @class = "form-horizontal" }))
                        {
                        }
                        <p><b><em>***TESLİMAT GÜNÜNDE İSTEK NUMARANIZ ÜSTÜNDEN TESLİMAT İŞLEMİ GERÇEKLEŞTİRİLECEKTİR.</em> </b></p>
                        <br />
                        @foreach (var istek in Model.Item1)
                        {
                            if (istek.aracId != null)
                            {
                                <fieldset>
                                    <p>
                                        <label>İstek Numaranız : <b>@istek.Id</b></label>
                                        <label align="right">İsteği Yaptığım Tarih:@istek.istekTarihi</label>
                                        <label><b>Plaka:</b>@istek.aracId.plaka</label>
                                        <label><b>Adı-Soyadı:</b>@istek.musteriId.ad @istek.musteriId.soyad</label>
                                        <label><b>Alım Tarihi:</b>@istek.planlananAlimTarihi - <b>Teslim Tarihi:</b>@istek.planlananTeslimTarihi</label>
                                        <label><b>Adı-Soyadı:</b> @istek.onayDurumu</label>
                                        <label align="right">Ödenecek Kiralama Ücreti : @istek.ucret <b>₺</b> </label>
                                    </p>

                                </fieldset>
                            }



                        }

                    </form>

                </div>

                <!-- // #main -->

                <div class="clear"></div>
            </div>
            <!-- // #container -->
        </div>
        <!-- // #containerHolder -->


    </div>
    <!-- // #wrapper -->
</body>
</html>